/* tslint:disable */
/* eslint-disable */
/**
 * Mealie
 * Mealie is a web application for managing your recipes, meal plans, and shopping lists. This is the Restful API interactive documentation that can be used to explore the API. If you\'re justing getting started with the API and want to get started quickly, you can use the [API Usage | Mealie Docs](https://hay-kot.github.io/mealie/documentation/getting-started/api-usage/) as a reference for how to get started.   As of this release <b>v1.0.0beta-5</b>, Mealie is still in rapid development and therefore some of these APIs may change from version to version.   If you have any questions or comments about mealie, please use the discord server to talk to the developers or other community members. If you\'d like to file an issue, please use the [GitHub Issue Tracker | Mealie](https://github.com/hay-kot/mealie/issues/new/choose)   ## Helpful Links - [Home Page](https://mealie.io) - [Documentation](https://hay-kot.github.io/mealie/) - [Discord](https://discord.gg/QuStdQGSGK) - [Demo](https://demo.mealie.io) - [Beta](https://demo.mealie.io)   
 *
 * The version of the OpenAPI document: v1.0.0beta-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./apis";
export * from "./common/configuration";

